version: '3.4'

services:
  postgresql:
    image: postgres:11.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hexagonalsample
      POSTGRES_PASSWORD: hexagonalsample
      POSTGRES_DB: hexagonalsample
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hexagonalsample"]
      interval: 10s
      timeout: 5s
      retries: 5